name: test
on:
  push:
    branches: [main]
jobs:
  ui-test:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"
      CI: "true"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Caching nodeJS
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install --ignore-scripts

      - name: End to End Test
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Setup Chrome
        inputs:
          chrome-version:
            default: latest
            required: false
        runs:
          using: "node14"
          main: "App.js"

      - run: npm ci
      - run: npm run build --if-present

      - run: npm test
